


data_location: "/home/wndzimbong/2022_2023/DOUBLE_ANNOTATION_DATA"

nnunet_data: "nnunet_seg_2tg_ctdata128"
modality: "ct"
channel_names:
          0: "CT"
# The labels to be used. The background must always be represented by '0' pixels, as recommended by nnUNet.
labels:
    "background": 0
    "kidney": 1

# The image file's extension
file_ending: ".nii.gz"
# The description of the task.
description: "kidney seg"
# NnUNet image reader that will be used.
image_reader_writer: "NibabelIOWithReorient"
# The dataset reference.
reference: "none"
# The dataset ID.
dataset_id: 07
# The name of the dataset.
task_name: "kidney128_seg_2tg"
# The image prefix
img_prefix: "kidney_"
# The channel names are required by nnUNet for image file name formatting
channel: "0000"

fold:
 # CT #
   cv1: ['a84', 'a116', 'a114', 'a98', 'a118', 'a04', 'a44', 'a101', 'a88',
         'b84', 'b116', 'b114', 'b98', 'b118', 'b04', 'b44', 'b101', 'b88']

   cv2: ['a47', 'a01', 'a74', 'a14', 'a33', 'a24', 'a72', 'a51', 'a64',
         'b47', 'b01', 'b74', 'b14', 'b33', 'b24', 'b72', 'b51', 'b64']

   cv3: ['a05', 'a57', 'a43', 'a94', 'a131', 'a11', 'a54', 'a12', 'a15', 'a17',
         'b05', 'b57', 'b43', 'b94', 'b131', 'b11', 'b54', 'b12', 'b15', 'b17']

   cv4: ['a21', 'a03', 'a97', 'a27', 'a23', 'a09', 'a61', 'a32', 'a53', 'a119',
         'b21', 'b03', 'b97', 'b27', 'b23', 'b09', 'b61', 'b32', 'b53', 'b119']

   cv5: ['a125', 'a20', 'a42', 'a99', 'a02', 'a87', 'a37', 'a38', 'a107', 'a31',
         'b125', 'b20', 'b42', 'b99', 'b02', 'b87', 'b37', 'b38', 'b107', 'b31']
