


data_location: "/home/wndzimbong/2022_2023/DOUBLE_ANNOTATION_DATA"

nnunet_data: "nnunet_seg_1tg_usdata128"
modality: "us"
channel_names:
          0: "US"
# The labels to be used. The background must always be represented by '0' pixels, as recommended by nnUNet.
labels:
    "background": 0
    "kidney": 1

# The image file's extension
file_ending: ".nii.gz"
# The description of the task.
description: "kidney seg"
# NnUNet image reader that will be used.
image_reader_writer: "NibabelIOWithReorient"
# The dataset reference.
reference: "none"
# The dataset ID.
dataset_id: 13
# The name of the dataset.
task_name: "kidney128_seg_1tg"
# The image prefix
img_prefix: "kidney_"
# The channel names are required by nnUNet for image file name formatting
channel: "0000"

fold:
  # US #
      cv1: ['84R', '84L', '116R', '116L', '114R', '98R', '98L', '118R', '118L', '04L', '44R', '44L']
      cv2: ['47R', '01R', '01L', '74R', '14R', '14L', '33L', '72L', '51R', '51L']
      cv3: ['05R', '57R', '57L', '43R', '43L', '94R', '131L', '11R', '11L', '54R', '12L', '15R', '17L']
      cv4: ['21R', '21L', '03R', '03L', '97R', '97L', '27R', '27L', '23R', '23L', '53L', '119R']
      cv5: ['125R', '125L', '20R', '42R', '99R', '02R', '02L', '87R', '87L', '37R', '38R', '38L']
