name: trusted
channels:
  - defaults
  - conda-forge
  - pytorch
  # - fastai
dependencies:
  - python==3.9 (OK)
  - pip (OK)
  # BASICS
  - numpy==1.25.2 (OK)
  - scikit-image==0.18.3 (OK)
  # - scipy
  # - pandas
  # - tqdm
  # - click
  # - ipython
  # VISUALIZATION
  - matplotlib (OK)
  # - ipympl  # interactive matplotlib plots
  # - seaborn
  # - altair
  # - yellowbrick
  # ML, STATS & DEEP LEARNING
  # - statsmodels
  # - scikit-learn
  # - sktime
  # - tslearn
  # - xgboost
  # - catboost
  # - lightgbm
  # - pytorch
  # - fastai  # activate fastai channel above!
  # - tensorflow
  # - keras
  # - spacy
  # OTHER TOOLS
  # - optuna
  # - dask
  # - snakeviz
  - pip:
     - -e .  # install git checkout of trusted_datapaper_ds in editable mode
     - monai==0.6.0 (OK)
     - natsort (OK)
     - open3d==0.17.0 (OK)
     - connected-components-3d==3.9.1 (OK)
     - simpleitk==2.3.1 (OK)
     - nibabel==3.2.2 (OK)
     - numpymaxflow==0.0.5 (OK)
     # add here only pip-packages that are not available in conda/conda-forge! E.g.:
     # - icecream
     # - jax
     # - numpyro
     # - funsor
     # - neptune-client
     # - neptune-contrib


  # DEVELOPMENT ONLY PACKAGES (could also be kept in a separate environment file)
  # - jupyterlab
  # - pytest
  # - pytest-cov
  # - tox
  # - pre_commit
  # - nbdime
  # - nbstripout
  # - sphinx
  # - recommonmark
