
data_location: "/home/TRUSTED_dataset_for_submission/"

## ''' US data FOLDERS PROVIDED'''
USimgfol: "US_DATA/US_images/"
USma1fol: "US_DATA/US_masks/Annotator1/"
USma2fol: "US_DATA/US_masks/Annotator2/"
USmagtfol: "US_DATA/US_masks/GT_estimated_masksUS/"
USme1fol: "US_DATA/US_meshes/Annotator1/"
USme2fol: "US_DATA/US_meshes/Annotator2/"
USmegtfol: "US_DATA/US_meshes/GT_estimated_meshesUS/"
USld1fol: "US_DATA/US_landmarks/Annotator1/"
USld2fol: "US_DATA/US_landmarks/Annotator2/"
USldgtfol: "US_DATA/US_landmarks/GT_estimated_ldksUS/"

USme1_inimg_fol: "US_DATA/US_meshes_inimg/Annotator1/"
USme2_inimg_fol: "US_DATA/US_meshes_inimg/Annotator2/"
USmegt_inimg_fol: "US_DATA/US_meshes_inimg/GT_estimated_meshesUS/"


## ''' CT data FOLDERS PROVIDED'''
CTimgfol: "CT_DATA/CT_images/"
CTma1fol: "CT_DATA/CT_masks/Annotator1/"
CTma2fol: "CT_DATA/CT_masks/Annotator2/"
CTmagtfol: "CT_DATA/CT_masks/GT_estimated_masksCT/"
CTme1fol: "CT_DATA/CT_meshes/Annotator1/"
CTme2fol: "CT_DATA/CT_meshes/Annotator2/"
CTmegtfol: "CT_DATA/CT_meshes/GT_estimated_meshesCT/"
CTld1fol: "CT_DATA/CT_landmarks/Annotator1/"
CTld2fol: "CT_DATA/CT_landmarks/Annotator2/"
CTldgtfol: "CT_DATA/CT_landmarks/GT_estimated_ldksCT/"

CTld1_inimg_fol: "CT_DATA/CT_landmarks_inimg/Annotator1/"
CTld2_inimg_fol: "CT_DATA/CT_landmarks_inimg/Annotator2/"
CTldgt_inimg_fol: "CT_DATA/CT_landmarks_inimg/GT_estimated_ldksCT/"

CTme1_inimg_fol: "CT_DATA/CT_meshes_inimg/Annotator1/"
CTme2_inimg_fol: "CT_DATA/CT_meshes_inimg/Annotator2/"
CTmegt_inimg_fol: "CT_DATA/CT_meshes_inimg/GT_estimated_meshesCT/"


## ''' Data name suffixes '''
USimg_end: "_imgUS.nii.gz"
USma_end: "_maskUS.nii.gz"
USme_end: "meshfaceUS.obj"
USld_end: "_ldkUS.txt"

CTimg_end: "_imgCT.nii.gz"
CTma_end: "_maskCT.nii.gz"
CTme_end: "meshfaceCT.obj"
CTld_end: "_ldkCT.txt"


## ''' Five-fold cross validation test set splits '''
CTfoldmask:
   cv1: ['263', '794', '592', '206', '579', '915', '250', '905', '249']
   cv2: ['561', '418', '636', '258', '283', '737', '610', '517', '801']
   cv3: ['443', '506', '641', '398', '711', '532', '371', '721', '735', '680']
   cv4: ['755', '510', '701', '948', '329', '239', '284', '656', '704', '399']
   cv5: ['861', '200', '220', '716', '348', '466', '738', '314', '832', '406']

CTfoldmesh:
   cv1: ['263R', '794R', '592R', '206R', '579R', '915R', '250R', '905R', '249R', '263L', '794L', '592L', '206L', '579L', '915L', '250L', '905L', '249L']
   cv2: ['561R', '418R', '636R', '258R', '283R', '737R', '610R', '517R', '801R', '561L', '418L', '636L', '258L', '283L', '737L', '610L', '517L', '801L']
   cv3: ['443R', '506R', '641R', '398R', '711R', '532R', '371R', '721R', '735R', '680R', '443L', '506L', '641L', '398L', '711L', '532L', '371L', '721L', '735L', '680L']
   cv4: ['755R', '510R', '701R', '948R', '329R', '239R', '284R', '656R', '704R', '399R', '755L', '510L', '701L', '948L', '329L', '239L', '284L', '656L', '704L', '399L']
   cv5: ['861R', '200R', '220R', '716R', '348R', '466R', '738R', '314R', '832R', '406R', '861L', '200L', '220L', '716L', '348L', '466L', '738L', '314L', '832L', '406L']

USfold:
   cv1: ['263R', '263L', '794R', '794L', '592R', '206R', '206L', '579R', '579L', '915L', '250R', '250L']
   cv2: ['561R', '418R', '418L', '636R', '258R', '258L', '283L', '610L', '517R', '517L']
   cv3: ['443R', '506R', '506L', '641R', '641L', '398R', '711L', '532R', '532L', '371R', '721L', '735R', '680L']
   cv4: ['755R', '755L', '510R', '510L', '701R', '701L', '948R', '948L', '329R', '329L', '704L', '399R']
   cv5: ['861R', '861L', '200R', '220R', '716R', '348R', '348L', '466R', '466L', '738R', '314R', '314L']


# WHERE YOU COULD SAVE YOUR CREATED DATA
myDATA: "/home/TRUSTED_dataset_for_submission/myDATA"

## ''' FOLDERS NO PROVIDED (Have to be created by used if need. Can be added)'''

CTspma1fol: "CT_DATA/CTsplit_masks/Annotator1/" # CT split masks
CTspma2fol: "CT_DATA/CTsplit_masks/Annotator2/"
CTspmagtfol: "CT_DATA/CTsplit_masks/GT_estimated_masksCT/"

CT0spma1fol: "CT_DATA/CTsplit_masks_origin0/Annotator1/" # CT split masks shifted to origin [0,0,0]
CT0spma2fol: "CT_DATA/CTsplit_masks_origin0/Annotator2/"
CT0spmagtfol: "CT_DATA/CTsplit_masks_origin0/GT_estimated_masksCT/"

CT0imgfol: "CT_DATA/CT_images_origin0/" # CT images shifted to origin [0,0,0]

CT_tbackldk_transforms: "CT_DATA/CT_tbackldk_transforms/"
CT_tbackmesh_transforms: "CT_DATA/CT_tbackmesh_transforms/"

CTldks_over_images: True
annotator_mov_ldks: "gt"  # can be "1", "2", or "gt"

CTmesh_over_images: False
USmesh_over_images: True
annotator_mov_mesh: "2"  # can be "1", "2", or "gt"


CT0ma1fol: "CT_DATA/CT_masks_origin0/Annotator1/" # CT masks shifted to origin [0,0,0]
CT0ma2fol: "CT_DATA/CT_masks_origin0/Annotator2/"
CT0magtfol: "CT_DATA/CT_masks_origin0/GT_estimated_masksCT/"

US128imgfol: "US_DATA/USimg128/"
US128ma1fol: "US_DATA/USmask128/Annotator1/"
US128ma2fol: "US_DATA/USmask128/Annotator2/"
US128magtfol: "US_DATA/USmask128/GT_estimated_masksUS/"

CT128imgfol: "CT_DATA/CTimg128/"
CT128ma1fol: "CT_DATA/CTmask128/Annotator1/"
CT128ma2fol: "CT_DATA/CTmask128/Annotator2/"
CT128magtfol: "CT_DATA/CTmask128/GT_estimated_masksCT/"


## ''' MAIN PROCESSINGS '''

# Mask ground-truth estimation (STAPLE fusion)
myUS_fusedmasks_location: "/home/TRUSTED_dataset_for_submission/myDATA/US_DATA/US_masks/GT_estimated_masksUS/"
myCT_fusedmasks_location: "/home/TRUSTED_dataset_for_submission/myDATA/CT_DATA/CT_masks/GT_estimated_maskCT/"
fuse_USmask: True
fuse_CTmask: False

# Landmarks ground-truth estimation
myUS_fusedlandmarks_location: "/home/TRUSTED_dataset_for_submission/myDATA/US_DATA/US_landmarks/GT_estimated_ldksUS/"
myCT_fusedlandmarks_location: "/home/TRUSTED_dataset_for_submission/myDATA/CT_DATA/CT_landmarks/GT_estimated_ldksCT/"
fuse_USlandmark: True
fuse_CTlandmark: True

# Mask to mesh
CTmask_to_mesh: False
USmask_to_mesh: True
annotator_mask_to_mesh: "gt" # can be "1", "2", or "gt"

# Split CT masks
splitCTmask: True
annotator_splitCTmask: "gt" # can be "1", "2", or "gt"

# Ground-truth comparison with annotators
US_analysis_folder: "US_analysis_folder"
CT_analysis_folder: "CT_analysis_folder"
usdata_eval: True
ctdata_eval: True

# Statistical summary
usdata_analysis: True
ctdata_analysis: True

# Data resizing (in preparation to the segmentation step)
usdata_resize: False
ctdata_resize: True
newsize: [128, 128, 128]
annotator_dataresize: "1" # can be "1", "2", or "gt"


# Shift CT images so that their origins become [0,0,0]. That will be useful to assess the registration
shiftCTimg_origin: True
