data_location: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/DOUBLE_ANNOTATION_DATA/TRUSTED_MedImA_submission"
output_location: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/DOUBLE_ANNOTATION_DATA"

auto: "auto"
modality: "CT"
img_location: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/DOUBLE_ANNOTATION_DATA/TRUSTED_MedImA_submission/CT_DATA/CT_images/"

gtmask_location: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/DOUBLE_ANNOTATION_DATA/TRUSTED_MedImA_submission/CT_DATA/CT_masks/GT_estimated_masksCT/"
gtsplitmask_location: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/DOUBLE_ANNOTATION_DATA/TRUSTED_MedImA_submission/CT_DATA/CTsplit_masks/GT_estimated_masksCT/"
gtmesh_location: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/DOUBLE_ANNOTATION_DATA/TRUSTED_MedImA_submission/CT_DATA/CT_meshes/GT_estimated_meshesCT"

ct128imgfol: "CT_DATA/CTimg128/"
ct128ma1fol: "CT_DATA/CTmask128/Annotator1/"
ct128ma2fol: "CT_DATA/CTmask128/Annotator2/"
ct128magtfol: "CT_DATA/CTmask128/GT_estimated_masksCT/"

seg128location: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/DOUBLE_ANNOTATION_DATA/CT_DATA/CToutput_mask128/"

mask_seglocation: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/DOUBLE_ANNOTATION_DATA/CT_DATA/CToutput_mask/"
splitmask_seglocation: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/DOUBLE_ANNOTATION_DATA/CT_DATA/CTsplit_output_mask/"
mesh_seglocation: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/DOUBLE_ANNOTATION_DATA/CT_DATA/CToutput_mesh/"
pcd_seglocation: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/DOUBLE_ANNOTATION_DATA/CT_DATA/CToutput_pcdTXT/"

segresults_folder: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/segmentation_benchmarks/CT/"

CTimg_end: "_imgCT.nii.gz"
CTma_end: "_maskCT.nii.gz"
CTme_end: "meshfaceCT.obj"

trained_models_location: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/DOUBLE_ANNOTATION_DATA/CT_DATA/CTseg_trained_models/"

trainsegmodel: "unet"

evalsegmodel: "cotr_loic_by_william"
# evalsegmodel: "vnet_lr1.0_epoch1001_batch2"

# training_target: "single_target_training"
training_target: "double_targets_training"

list_segmodels: ["vnet_lr1.0_epoch1001_batch4", "unet_lr1.0_epoch1001_batch4", "vnet_lr1.0_epoch1001_batch2", "unet_lr1.0_epoch1001_batch2"]
list_training_target: ["single_target_training", "double_targets_training"]


cv1: ['84', '116', '114', '98', '118', '04', '44', '101', '88']
cv2: ['47', '01', '74', '14', '33', '24', '72', '51', '64']
cv3: ['05', '57', '43', '94', '131', '11', '54', '12', '15', '17']
cv4: ['21', '03', '97', '27', '23', '09', '61', '32', '53', '119']
cv5: ['125', '20', '42', '99', '02', '87', '37', '38', '107', '31']
