modality: "CT"
auto: "auto"

data_location: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/DOUBLE_ANNOTATION_DATA/TRUSTED_submission"
img_location: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/DOUBLE_ANNOTATION_DATA/TRUSTED_submission/CT_DATA/CT_images/"

output_location: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/DOUBLE_ANNOTATION_DATA/TRUSTED_submission/myDATA"

# Cross validation splits
cv1: ['84', '116', '114', '98', '118', '04', '44', '101', '88']
cv2: ['47', '01', '74', '14', '33', '24', '72', '51', '64']
cv3: ['05', '57', '43', '94', '131', '11', '54', '12', '15', '17']
cv4: ['21', '03', '97', '27', '23', '09', '61', '32', '53', '119']
cv5: ['125', '20', '42', '99', '02', '87', '37', '38', '107', '31']

# CT data suffixes
CTimg_end: "_imgCT.nii.gz"
CTma_end: "_maskCT.nii.gz"
CTme_end: "meshfaceCT.obj"

# For UNet and VNet training
trainsegmodel: "unet" # or "vnet"
training_target: "double_targets_training" # or "single_target_training"
# The list of the test folders, in a 5-fold cross-validation prespective
cv_list: ['cv1', 'cv2', 'cv3', 'cv4', 'cv5']

# Resized ([128-128-128]) training data
CT128imgfol: "CT_DATA/CTimg128/"
CT128ma1fol: "CT_DATA/CTmask128/Annotator1/"
CT128ma2fol: "CT_DATA/CTmask128/Annotator2/"
CT128magtfol: "CT_DATA/CTmask128/GT_estimated_masksCT/"

# Location of the training weight
trained_models_location: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/DOUBLE_ANNOTATION_DATA/CT_DATA/CTseg_trained_models/"

# For UNet and VNet inference
list_UVnetmodels: ["vnet_lr1.0_epoch1001_batch2", "unet_lr1.0_epoch1001_batch2"]
list_training_target: ["single_target_training", "double_targets_training"]

# Resized (into [128-128-128]) output masks from nnunet and cotr trained models
seg128location: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/DOUBLE_ANNOTATION_DATA/CT_DATA/CToutput_mask128/"

# Automatic segmentation post-processing
list_othermodels: ["nnunet", "cotr"]
upsampling: True # just for nnunet and cotr
meshing: True
splitCT: True

# Output masks from trained models with their original size, and the corresponding split masks, meshes and point clouds
mask_seglocation: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/DOUBLE_ANNOTATION_DATA/CT_DATA/CToutput_mask/"
splitmask_seglocation: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/DOUBLE_ANNOTATION_DATA/CT_DATA/CTsplit_output_mask/"
mesh_seglocation: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/DOUBLE_ANNOTATION_DATA/CT_DATA/CToutput_mesh/"
pcd_seglocation: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/DOUBLE_ANNOTATION_DATA/CT_DATA/CToutput_pcdTXT/"

# Ground-truth masks with their original size, split masks and meshes for evaluation
gtmask_location: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/DOUBLE_ANNOTATION_DATA/TRUSTED_submission/CT_DATA/CT_masks/GT_estimated_masksCT/"
gtsplitmask_location: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/DOUBLE_ANNOTATION_DATA/TRUSTED_submission/CT_DATA/CTsplit_masks/GT_estimated_masksCT/"
gtmesh_location: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/DOUBLE_ANNOTATION_DATA/TRUSTED_submission/CT_DATA/CT_meshes/GT_estimated_meshesCT"

# Segmentation evaluation results
segresults_folder: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/segmentation_benchmarks/CT/"
