auto: "auto"
modality: "CT"

ref1model: "nnunet"
ref1target: "double_targets_training"

ref2model: "cotr"
ref2target: "single_target_training"

segresults_folder: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/segmentation_benchmarks/CT/"

cv1: ['84R', '116R', '114R', '98R', '118R', '04R', '44R', '101R', '88R', '84L', '116L', '114L', '98L', '118L', '04L', '44L', '101L', '88L']
cv2: ['47R', '01R', '74R', '14R', '33R', '24R', '72R', '51R', '64R', '47L', '01L', '74L', '14L', '33L', '24L', '72L', '51L', '64L']
cv3: ['05R', '57R', '43R', '94R', '131R', '11R', '54R', '12R', '15R', '17R', '05L', '57L', '43L', '94L', '131L', '11L', '54L', '12L', '15L', '17L']
cv4: ['21R', '03R', '97R', '27R', '23R', '09R', '61R', '32R', '53R', '119R', '21L', '03L', '97L', '27L', '23L', '09L', '61L', '32L', '53L', '119L']
cv5: ['125R', '20R', '42R', '99R', '02R', '87R', '37R', '38R', '107R', '31R', '125L', '20L', '42L', '99L', '02L', '87L', '37L', '38L', '107L', '31L']
