
refmethod: "BCPD" # It is the reference method
reftransform: "affine"

list_regmethods: ["ICP", "BCPD", "imfLNCC", "imfLC2", "TransMorph"]
list_regtransforms: ["rigid", "affine"]

regresults_folder: "/home/TRUSTED_dataset_for_submission/reg_results"

cv1: ['263R', '263L', '794R', '794L', '592R', '206R', '206L', '579R', '579L', '915L', '250R', '250L']
cv2: ['561R', '418R', '418L', '636R', '258R', '258L', '283L', '610L', '517R', '517L']
cv3: ['443R', '506R', '506L', '641R', '641L', '398R', '711L', '532R', '532L', '371R', '721L', '735R', '680L']
cv4: ['755R', '755L', '510R', '510L', '701R', '701L', '948R', '948L', '329R', '329L', '704L', '399R']
cv5: ['861R', '861L', '200R', '220R', '716R', '348R', '348L', '466R', '466L', '738R', '314R', '314L']

# For analysis of noising on registration
list_std: [0, 2, 4, 6, 8, 10]
