
# The folder where the GT landmarks in .txt are located
USldks_location: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/DOUBLE_ANNOTATION_DATA/TRUSTED_submission/US_DATA/US_landmarks/GT_estimated_ldksUS/"
CTldks_location: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/DOUBLE_ANNOTATION_DATA/TRUSTED_submission/CT_DATA/CT_landmarks/GT_estimated_ldksCT/"

# Where you like to create the folders that will content the estimated transformations
transfo_location: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/DOUBLE_ANNOTATION_DATA/TRUSTED_submission/"

# Where you like to create the folders that will content the different results csv files
regresults: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/DOUBLE_ANNOTATION_DATA/TRUSTED_submission/reg_results"

# The transform model for landmarks (global) registration
ldks_model: "similarity"

# The noise introduce in the moving landmarks position
noise_std: 0 # Values are in [0, 2, 4, 6, 8, 10]

# The transform model for registration refinement
refine_model: "affine" # or "rigid"

# The surface based registration method
regmethod: "ICP" # or BCPD

# The similarity_metric for ImFusion intensity-based method:
similarity_metric: "LNCC" # or "LC2"

# The number of registration repetitions you want to run per pairs of volumes.
# Must be at leat equal to 1
# If noise_std is 0, iternumb must be equl to 1
iternumb: 1

# For surface-based refinement
USautomesh_location: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/DOUBLE_ANNOTATION_DATA/US_DATA/USoutput_mesh/"
CTautomesh_location: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/DOUBLE_ANNOTATION_DATA/CT_DATA/CToutput_mesh/"

segmodel: "nnunet"  # ALWAYS (in our case)
training_target: "double_targets_training"  # ALWAYS (in our case)

bcpd_temp_folder: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/DOUBLE_ANNOTATION_DATA/TRUSTED_submission/bcdp_temp_folder"
regpack_dir: "src/trusted_datapaper_ds/registration"

# For intensity-based refinement
USimg_location: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/DOUBLE_ANNOTATION_DATA/TRUSTED_submission/US_DATA/US_images/"
CTimg_location: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/DOUBLE_ANNOTATION_DATA/TRUSTED_submission/CT_DATA/CT_images/"

imf_temp_folder: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/DOUBLE_ANNOTATION_DATA/TRUSTED_submission/imf_temp_folder"

# For evaluation
USgtmesh_location: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/DOUBLE_ANNOTATION_DATA/TRUSTED_submission/US_DATA/US_meshes/GT_estimated_meshesUS/"
CTgtmesh_location: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/DOUBLE_ANNOTATION_DATA/TRUSTED_submission/CT_DATA/CT_meshes/GT_estimated_meshesCT/"

CTimg_origin0_location: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/DOUBLE_ANNOTATION_DATA/TRUSTED_submission/CT_DATA/CTimg_origin0/"

refinement_methods: ["BCPD", "ICP", "imfLNCC", "imfLC2"]
transform_models: ["affine", "rigid"]
std_cases: ["0.0", "2.0", "4.0", "6.0", "8.0", "10.0"]
