auto: "auto"
modality: "US"

refmodel: "nnunetv1_loic"
reftarget: "double_targets_training"

list_evalsegmodels: ["unet_lr1.0_epoch1001_batch4", "vnet_lr1.0_epoch1001_batch4", "nnunetv1_loic", "cotr_loic"]
list_training_target: ["single_target_training", "double_targets_training"]

segresults_folder: "/home/wndzimbong/IRCAD_DOSSIER/2022_2023/segmentation_benchmarks/"

ctcv1: ['84R', '116R', '114R', '98R', '118R', '04R', '44R', '101R', '88R', '84L', '116L', '114L', '98L', '118L', '04L', '44L', '101L', '88L']
ctcv2: ['47R', '01R', '74R', '14R', '33R', '24R', '72R', '51R', '64R', '47L', '01L', '74L', '14L', '33L', '24L', '72L', '51L', '64L']
ctcv3: ['05R', '57R', '43R', '94R', '131R', '11R', '54R', '12R', '15R', '17R', '05L', '57L', '43L', '94L', '131L', '11L', '54L', '12L', '15L', '17L']
ctcv4: ['21R', '03R', '97R', '27R', '23R', '09R', '61R', '32R', '53R', '119R', '21L', '03L', '97L', '27L', '23L', '09L', '61L', '32L', '53L', '119L']
ctcv5: ['125R', '20R', '42R', '99R', '02R', '87R', '37R', '38R', '107R', '31R', '125L', '20L', '42L', '99L', '02L', '87L', '37L', '38L', '107L', '31L']


uscv1: ['84R', '84L', '116R', '116L', '114R', '98R', '98L', '118R', '118L', '04L', '44R', '44L']
uscv2: ['47R', '01R', '01L', '74R', '14R', '14L', '33L', '72L', '51R', '51L']
uscv3: ['05R', '57R', '57L', '43R', '43L', '94R', '131L', '11R', '11L', '54R', '12L', '15R', '17L']
uscv4: ['21R', '21L', '03R', '03L', '97R', '97L', '27R', '27L', '23R', '23L', '53L', '119R']
uscv5: ['125R', '125L', '20R', '42R', '99R', '02R', '02L', '87R', '87L', '37R', '38R', '38L']
