auto: "auto"
modality: "US"

data_location: "/home/TRUSTED_dataset_for_submission"
img_location: "/home/TRUSTED_dataset_for_submission/US_DATA/US_images/"

output_location: "/home/TRUSTED_dataset_for_submission/myDATA"

# Cross validation splits
cv1: ['263R', '263L', '794R', '794L', '592R', '206R', '206L', '579R', '579L', '915L', '250R', '250L']
cv2: ['561R', '418R', '418L', '636R', '258R', '258L', '283L', '610L', '517R', '517L']
cv3: ['443R', '506R', '506L', '641R', '641L', '398R', '711L', '532R', '532L', '371R', '721L', '735R', '680L']
cv4: ['755R', '755L', '510R', '510L', '701R', '701L', '948R', '948L', '329R', '329L', '704L', '399R']
cv5: ['861R', '861L', '200R', '220R', '716R', '348R', '348L', '466R', '466L', '738R', '314R', '314L']

# US data suffixes
USimg_end: "_imgUS.nii.gz"
USma_end: "_maskUS.nii.gz"
USme_end: "meshfaceUS.obj"

# For UNet and VNet training
trainsegmodel: "unet" # or "vnet"
training_target: "double_targets_training" # or "single_target_training"
# The list of the test folders, in a 5-fold cross-validation prespective
cv_list: ['cv1', 'cv2', 'cv3', 'cv4', 'cv5']

# Resized ([128-128-128]) training data
US128imgfol: "US_DATA/USimg128/"
US128ma1fol: "US_DATA/USmask128/Annotator1/"
US128ma2fol: "US_DATA/USmask128/Annotator2/"
US128magtfol: "US_DATA/USmask128/GT_estimated_masksUS/"

# Location of the training weight
trained_models_location: "/home/TRUSTED_dataset_for_submission/US_DATA/USseg_trained_models/"

# For UNet and VNet inference
list_UVnetmodels: ["vnet_lr1.0_epoch1001_batch2", "unet_lr1.0_epoch1001_batch2"]
list_training_target: ["single_target_training", "double_targets_training"]

# Resized (into [128-128-128]) output masks from nnunet and cotr trained models
seg128location: "/home/TRUSTED_dataset_for_submission/US_DATA/USoutput_mask128/"

# Automatic segmentation post-processing
list_othermodels: ["nnunet", "cotr"]
upsampling: True # just for nnunet and cotr
meshing: True
splitCT: True

# Output masks from trained models with their original size, and the corresponding split masks, meshes and point clouds
mask_seglocation: "/home/TRUSTED_dataset_for_submission/US_DATA/USoutput_mask/"
mesh_seglocation: "/home/TRUSTED_dataset_for_submission/US_DATA/USoutput_mesh/"
pcd_seglocation: "/home/TRUSTED_dataset_for_submission/US_DATA/USoutput_pcdTXT/"

# Ground-truth masks with their original size, split masks and meshes for evaluation
gtmask_location: "/homeTRUSTED_submission/US_DATA/US_masks/GT_estimated_masksUS/"
gtmesh_location: "/home/TRUSTED_dataset_for_submission/US_DATA/US_meshes/GT_estimated_meshesUS"

# Segmentation evaluation results
segresults_folder: "/home/TRUSTED_dataset_for_submission/segmentation_benchmarks/US/"
